# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146P0U3SlZSzOlAKwO_iDhfjO5NQzmYXL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits=load_digits()

dir(digits)

for i in range (5):
  plt.matshow(digits.images[i])

d = pd.DataFrame(digits.data)
d.head()

t=digits.target
t

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(d,t,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=60)
model.fit(X_train, y_train)

model.score(X_test, y_test)

